### PR TITLE
Russian translation

### PR DESCRIPTION
**Pull request by bigscoop**
added russian translation
couple of small fixes

### CODE REVIEW

**Comment by kallies** [comment]
Can you please flag the PR as "WIP" and squash the commits when ready?

**Comment by bigscoop** [comment]
well, I don't have any rights to flag or squash the PR. Btw, translation is ready, the rest I'm doing in another branch

**Comment by kallies** [comment]
You can `rebase -i`, squash and `push --force`

**Comment by bigscoop** [comment]
@kallies done

**Comment by bigscoop** [comment]
I'm done, pls review

**Comment by kallies** [comment]
Can you check the travis CI run (GeoIP issues)? Not checked: is a rebase against master needed?

**Comment by bigscoop** [comment]
I have no idea why the file is missing and also don't have any acces to travis :(

**Comment by psunix** [comment]
fixed conflicts, merged with https://github.com/puzzle/cryptopus/commit/d8058929ecb6fc4bb10599e8cf0f87ce53023c5e

**Pull request closed without merging**
