### PR TITLE
improve random password generator, fix browser password saving issues refs #133

### PR DESCRIPTION
**Pull request by psunix**

### CODE REVIEW

**Comment by psunix** [comment]
replaces PR #150 and fixes issues described in #133 
could you please test it with different browsers? Edge, Firefox, Chrome, maybe also Sarafi.
Cheers

**Comment by psunix** [comment]
@TheWalkingLeek could you do a review on this feature? 
especially some cross browser testing would be nice.

**Comment by psunix** [comment]
@Robin481 might @TheWalkingLeek review this feature during work?
this fix would increase the user's experience a lot :)

**Comment by Robin481** [comment]
@psunix Sure, will be planned into the next sprint.

**Pull request merged**
